name: Demo CI for Go  # Naming the workflow
on: # listen for triggering event
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: # jobs to execute
  build: # name of the job
    name: Load container # job name
    runs-on: ubuntu-20.04 # os to run in container
    steps: # defined steps
    - name: Print Hello
      run: |
        ls
        echo "Hello, there!!"
    - name: Setup Go
      uses:  actions/setup-go@v3.2.0
      with: 
        go-version: 1.18
    - name: Check Go Version
      run: go version
    - name: Checkout Repo
      uses: actions/checkout@v2.4.2
    - name: Checkout Remote Private Repo
      uses: actions/checkout@v2.4.2
      with: 
        repository: lowkh2/GoSchoolRemoteExample
        token: ${{secrets.GO_SECRET}}
        path: remote
    - name: Check File System - remote
      run: |
        cd remote
        ls
        cat myText.txt
    - name: Check File System
      run: ls
    - name: Install dependencies
      run: |
        go mod init github.com/go-qiu/go-cicd-demo
        go get github.com/franela/goblin
        go mod tidy
        go test -v
